# Generated by Django 5.0.2 on 2024-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_planner', '0003_remove_fitnessgoal_weight_weighttracking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplanexercise',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
